### ISSUE TITLE
wrong event order with 3 components

### ISSUE THREAD

**Issue by franck-malka** [mobius-software-ltd/corsac-jss7#8]
I observed that sometimes, the onDialogRelease reach the application before all the components are processed.

I would have expected to the the onDialogRelease event only after the 3 components of the messages are delivered to the application.

I can say when it happens and when it doesn't.

Did you ever faced this issue?

**Comment by yulianoifa-mobius** [comment]
Release Event is not related to components. It is being sent when dialog state is set to Purged. 
Since the events are unrelated they may be coming in any order
